name: Docker Testing

on:
  push:
    branches:
    - main
    - develop 
  pull_request:
    branches: [ develop ]

jobs:
  docker-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ubuntu Version
        run: cat /etc/os-release

      - name: Docker Version
        run: docker version

      - name: Docker Compose Build and Up
        run: |
          cp .env.template .env
          docker-compose build
          docker-compose up -d

      - name: Docker Compose Process
        run: docker-compose ps -a